ops:
  top_lines_html_table_for_all_women:
    config:
      top_n: 5000
      start_date: 2025-01-01
      end_date: 2025-01-01
resources:
  database:
    config:
      database:
        env: DUCKDB_DATABASE
  storage:
    config:
      filepath:
        env: LOCAL_STORAGE_PATH
  templates:
    config:
      searchpath:
        env: JINJA_TEMPLATES_PATH

